name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      with:
        version-file: emqx-plugin-templates/.tool-versions
        version-type: strict
    - name: Check template code formatting
      run: make fmt-template-check
    - name: Check formatting of the project code (tests, rebar.config, etc)
      run: make fmt-check
    - name: Install rebar3 template
      run: make install-rebar-template
    - name: Build test plugin
      run: |
        git clone -b release-60 "https://github.com/emqx/emqx.git" /tmp/emqx
        export ERL_LIBS=/tmp/emqx/apps
        ./scripts/build-sample-plugin.sh \
          --tag 1.0.0 \
          --name my_emqx_plugin_avsc \
          --with-avsc \
          --build-dir /tmp/emqx/plugins \
          --output-dir /tmp/emqx/plugins/ \
          --no-cleanup-build-dir
        cd /tmp/emqx/plugins/my_emqx_plugin_avsc
        make dialyzer

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      ## We purposely do not use docker image for building,
      ## thus verifying that .tool-versions is suitable for developing a plugin.
    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      with:
        version-file: emqx-plugin-templates/.tool-versions
        version-type: strict
    - name: Install rebar3 template
      run: make install-rebar-template
    - name: Prepare EMQX monorepo layout
      run: |
        git clone -b release-60 "https://github.com/emqx/emqx.git" /tmp/emqx
    - name: Build test plugins
      run: |
        export ERL_LIBS=/tmp/emqx/apps
        make build-test-plugins PLUGIN_BUILD_DIR=/tmp/emqx/plugins
    - name: Start EMQX
      run: make up
    - name: Run tests
      run: make ct
    - name: Stop EMQX
      if: always()
      run: make down
